// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockService.Infrastructure.Persistence.AppDbContexts;

#nullable disable

namespace StockService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227135200_CreateStockItem")]
    partial class CreateStockItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockService.Domain.Locals.Entities.Local", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("locals", (string)null);
                });

            modelBuilder.Entity("StockService.Domain.Products.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("StockService.Domain.Stocks.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("ProductId");

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("StockService.Domain.Stocks.Entities.Stock", b =>
                {
                    b.HasOne("StockService.Domain.Locals.Entities.Local", "Local")
                        .WithMany("Stocks")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockService.Domain.Products.Entities.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("StockService.Domain.Stocks.StockItems.Entities.StockItem", "StockItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("decimal(12, 6)");

                            b1.Property<Guid>("StockId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("StockId");

                            b1.ToTable("stock_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("Local");

                    b.Navigation("Product");

                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("StockService.Domain.Locals.Entities.Local", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("StockService.Domain.Products.Entities.Product", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
